name: deployment

on: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile

      - run: BASE_PATHNAME="" yarn build

      - run: yarn surge ./dist $SHA-mm.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SHA: ${{ github.sha }}

      - run: yarn add @octokit/request@5.4.2

      - name: update deployment status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          node --unhandled-rejections=strict -e "
            const { request } = require('@octokit/request');
            const environment_url = '$SHA-mm.surge.sh';

            const { data: deployments } = await request('POST /repos/$REPOSITORY/deployments', {
              headers: { authorization: 'token $TOKEN' },
              sha: '$SHA',
            });

            const [deployment] = deployments;

            await request(`POST /repos/$REPOSITORY/deployments/${deployment.id}/statuses`, {
              headers: { authorization: 'token $TOKEN' },
              state: 'success',
              auto_inactive: true,
              environment_url,
            });"
