name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn type
      - run: yarn lint
      - run: yarn test --ci
      - run: ( cd packages/benchmark ; yarn start 6 4 60 )

  create-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn add @octokit/request@5.4.2

      - name: create deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          node --unhandled-rejections=strict -e "
            require('@octokit/request').request('POST /repos/$REPOSITORY/deployments', {
              headers: { authorization: 'token $GITHUB_TOKEN' },
              ref: '$SHA',
              environment: 'preview',
              required_contexts: []
            });"
