name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn type
      - run: yarn lint
      - run: yarn test --ci
      - run: ( cd packages/benchmark ; yarn start 60 )
